ALTER TABLE `offers` ADD COLUMN `updated_at` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `offers` ADD COLUMN `sku` VARCHAR(45) NOT NULL DEFAULT '';
ALTER TABLE `offers` ADD COLUMN `sold_out` TINYINT(1) NOT NULL DEFAULT 0;